# Site settings
title: Portfolio
description: Caleb's portfolio

# User settings
username: Caleb Stout
user_description: Hello! I'm Caleb, a Support Engineer at Qualtrics with a deep passion for security and project management. Leveraging my experience in addressing complex technical issues, I'm eager to innovate in the realms of digital security and efficient project delivery. Let's work together to create resilient and agile solutions.
user_title: Security & Project Management Specialist
email: hisurfingc911@gmail.com
twitter_username: https://twitter.com/norsie3
github_username: https://github.com/Nors1e

exclude: ['package.json', 'src' , 'node_modules']
