# Site settings
title: Portfolio
description: Caleb's portfolio

# User settings
username: Caleb Stout
user_description: Hello, my name is Caleb, I am an up and coming data scientist. I went to University of California, Santa Cruz to become a UX Researcher; instead I came out a scientist with fundamental skills learned both in my degree program and through LinkedIn eLearning, Udemy, and Google.
user_title: Data Engineer
email: hisurfingc@yahoo.com
twitter_username: https://twitter.com/norsie3
github_username: https://github.com/Nors1e

exclude: ['package.json', 'src' , 'node_modules']
